name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
      - beta
      - 'sdk-release/**'
      - 'feature/**'
      - development
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - master
      - beta
      - 'sdk-release/**'
      - 'feature/**'
      - development

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        id: setup-jre
        uses: actions/setup-java@v4
        with:
          java-version: "17" # always use 17 LTS for building
          distribution: zulu
          architecture: x64

      - name: Set Test Java Runtime Environment variable
        run: echo "JAVA_TEST_HOME=${{ steps.setup-jre.outputs.path }}" >> $GITHUB_ENV

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn clean install -DskipTests

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - "8"
          - "11"
          - "17"
          - "18"
          - "19"
          - "20"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Test Java Runtime
        id: setup-test-jre
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: zulu
          architecture: x64

      - name: Set Test Java Runtime Environment variable
        run: echo "JAVA_TEST_HOME=${{ steps.setup-test-jre.outputs.path }}" >> $GITHUB_ENV

      - name: Display version
        run: echo "JAVA_TEST_HOME=$JAVA_TEST_HOME"

      - name: Cache Maven dependencies for tests
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.java-version }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run test suite
        run: mvn --batch-mode --update-snapshots verify

