name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
      - beta
      - 'sdk-release/**'
      - 'feature/**'
      - development
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - master
      - beta
      - 'sdk-release/**'
      - 'feature/**'
      - development

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17" # always use 17 LTS for building
          distribution: zulu
          architecture: x64

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/src/**') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Save Maven build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: maven-artifacts
          path: target/

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build  # Ensure build job runs before this one

    strategy:
      fail-fast: false
      matrix:
        java-version: ["8", "11", "17", "18", "19", "20"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: maven-artifacts

      - name: Setup Test Java Runtime
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: zulu
          architecture: x64

      - name: Cache Maven dependencies for tests
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.java-version }}-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/src/**') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run test suite
        run: mvn --batch-mode --update-snapshots verify

