name: Daily Test

on:
  schedule:
    - cron: '0 3 * * *' 

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version: ["8", "11", "17", "18", "19", "20"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Test Java Runtime
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: zulu
          architecture: x64

      - name: Cache Maven dependencies for tests
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.java-version }}-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/src/**') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run test suite
        env:
          CORBADO_PROJECT_ID: ${{ secrets.CORBADO_PROJECT_ID }}
          CORBADO_API_SECRET: ${{ secrets.CORBADO_API_SECRET }}
          CORBADO_FRONTEND_API: ${{ vars.CORBADO_FRONTEND_API }}
          CORBADO_BACKEND_API: ${{ vars.CORBADO_BACKEND_API }}
        run: mvn --batch-mode --update-snapshots verify -DskipInstall 
